---
- name: check psql data dir
  stat: path=/var/lib/pgsql/9.6/data/pg_hba.conf
  register: is_exists

- name: postgresql initdb
  shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  become: yes
  when: not is_exists.stat.exists

- name: postgresql start
  service: name=postgresql-9.6 state=started
  become: yes
